feat:  adding activation inside universal.sh
atsign-foundation/noports pull request #1266
Opened 2024-08-19 12:47 UTC by Xlin123

**- What I did**
 introduced a check for activated / inactivated keys in order to improve the work flow of a fresh install.
**- How I did it**
  added a check inside client and device installation using at_activate.
**- How to verify it**
`git checkout xlin-activate-installer`
`./universal.sh`
**- Description for the changelog**
feat:  adding activation inside universal.sh

2024-08-19 14:15 UTC, XavierChanth approved these changes
TY

2024-08-19 14:18 UTC, xavierchanth commented on packages/dart/sshnoports/bundles/universal.sh
> +  validate_activation
Wait, we don't want to prompt them to activate their MPKAM on the device, only if it's client. The recommended (and thus automated approach) should always be APKAM to the device - only if someone know what they are doing, and thus can do it manually should they be putting MPKAM keys on a device.

2024-08-19 14:18 UTC, XavierChanth requested changes
See comment above

2024-08-19 15:08 UTC, Xlin123 commented on packages/dart/sshnoports/bundles/universal.sh
> +  validate_activation
was supposed to remove that after the arch convo on thursday, thanks for catching that

2024-08-21 16:23 UTC, XavierChanth approved these changes

2024-08-21 18:48 UTC, merged