fix: add onboarding screen to npt flutter
atsign-foundation/noports pull request #1428
Opened 2024-10-07 12:37 UTC by CurtlyCritchlow

**- What I did**
added onboarding screen and dialog to npt_flutter
**- How I did it**

**- How to verify it**
run the app and onboard.
**- Description for the changelog**

2024-10-07 14:51 UTC, XavierChanth approved these changes

2024-10-07 14:52 UTC, XavierChanth requested changes, later dismissed
Just the one change - move the root domain dialog out of main flow

2024-10-11 20:23 UTC, XavierChanth commented
There are some edge cases I caught when testing. I will make those changes early next week.

2024-10-16 21:55 UTC, gkc approved these changes

2024-10-16 21:57 UTC, merged