docs: usage section
atsign-foundation/noports pull request #22
Opened 2022-07-11 19:46 UTC by JeremyTubongbanua

**- What I did**
Add usage instructions for `sshnpd` and `sshnp`

**- How I did it**
Edit `README.md` (see changes)

**- How to verify it**
**Daemon instructions (sshnpd)**
![image](https://user-images.githubusercontent.com/79019866/178345209-73cf2b75-a1b3-49df-bed1-947af8fe69ee.png)

**Client instructions (sshnp)**
![image](https://user-images.githubusercontent.com/79019866/178345291-b36132c9-5710-411b-b9d0-ed39a05fd183.png)

2022-07-11 19:46 UTC, JeremyTubongbanua commented
@L1AMcB 

If you could be my 2nd pair of eyes, that would be great!

SSHNPD
![image](https://user-images.githubusercontent.com/79019866/178345926-ed58d543-f837-4f03-8030-66e7e1ca69f0.png)



SSHNP
![image](https://user-images.githubusercontent.com/79019866/178345979-5dadc051-5df6-4e8f-baae-6eaec18e4a50.png)

2022-07-11 21:28 UTC, L1AMcB requested changes
I believe the description section of SSHNPD that says  for -m, -manager (mandatory), "Managers atSign" should be changed to "Manager's atSign" since the noun is singular. 

Other than that looks great to me!

2022-07-11 22:33 UTC, L1AMcB requested changes
Only comment is that some of the descriptions start with a lowercase and some are uppercase in the sshnpd section while all of the descriptions in the sshnp section start with an uppercase. 

Other than that on line 115 the description for local port says "ssh port to listen on, on your local machine", is "listen on" a destination or is having "on" twice a typo?

Otherwise looks good!

2022-07-12 08:46 UTC, cpswan requested changes

2022-07-12 08:46 UTC, cpswan commented on README.md
> +dart bin/sshnp.dart <args|flags>
use `dart run` here as above

2022-07-12 08:46 UTC, cpswan commented on README.md
> +```
code fences might look better with language specified e.g. `sh` or `bash`

2022-07-12 16:59 UTC, cpswan approved these changes

2022-07-12 17:00 UTC, JeremyTubongbanua commented
> Only comment is that some of the descriptions start with a lowercase and some are uppercase in the sshnpd section while all of the descriptions in the sshnp section start with an uppercase.
> 
> Other than that on line 115 the description for local port says "ssh port to listen on, on your local machine", is "listen on" a destination or is having "on" twice a typo?
> 
> Otherwise looks good!

Hmm yeah the wording is a bit weird, but I think it's still right.
It's saying that the local port you provide will be the reverse ssh port to listen on, and the port must be on your local machine

2022-07-12 22:01 UTC, merged