chore: move ssh-client & legacy-daemon from core to cli only
atsign-foundation/noports pull request #592
Opened 2023-11-27 22:05 UTC by XavierChanth

**- What I did**

- Removed legacy-daemon and ssh-client args from the noports_core package and created an extended parser for them in the CLI
- Did a minor refactor of the main file

**- How I did it**

**- How to verify it**

**- Description for the changelog**
chore: move ssh-client & legacy-daemon from core to cli only

2023-11-27 22:21 UTC, XavierChanth commented on packages/sshnoports/bin/sshnp.dart
> -          namespace: '${params.device}.sshnp',
This line got removed because this value is already set by SshnpCore

2023-11-27 22:51 UTC, gkc requested changes
Checks are failing ...

2023-11-28 00:36 UTC, XavierChanth commented
> Checks are failing ...

Sorry, missed a cast from String to the SupportedSshClient enum type.

2023-11-28 12:00 UTC, gkc commented on packages/noports_core/lib/src/sshnp/models/sshnp_params.dart
> +      // legacyDaemon: params2.legacyDaemon ?? params1.legacyDaemon,
should be removed

2023-11-28 12:00 UTC, gkc commented on packages/noports_core/lib/src/sshnp/models/sshnp_params.dart
> +      // sshClient: params2.sshClient ?? params1.sshClient,
should be removed

2023-11-28 12:07 UTC, gkc commented on packages/noports_core/lib/src/sshnp/models/sshnp_params.dart
> +      // legacyDaemon: params2.legacyDaemon ?? params1.legacyDaemon,
Have removed

2023-11-28 12:07 UTC, gkc commented on packages/noports_core/lib/src/sshnp/models/sshnp_params.dart
> +      // sshClient: params2.sshClient ?? params1.sshClient,
Have removed

2023-11-28 12:10 UTC, gkc approved these changes
LGTM thanks @XavierChanth. FYI I pushed another commit to remove a couple of lines of dead commented code

2023-11-28 12:14 UTC, merged